use northwind;
select * from products;
select ProductID as 'Product Id' ,ProductName as 'Product Name' ,UnitPrice as 'Unit Price' from products;
select ProductID as 'Product Id' ,ProductName as 'Product Name' ,UnitPrice as 'Unit Price' from products order by UnitPrice;
select ProductID as 'Product Id' ,ProductName as 'Product Name' ,UnitPrice as 'Unit Price' from products where UnitPrice<=7.5;
select * from products where UnitsInStock >=100 order by UnitPrice desc;
select * from products where UnitsInStock >=100 order by UnitPrice desc,ProductName;
select * from products where UnitsInStock = 0 and UnitsOnOrder>=1 order by ProductName;
select * from Categories;
select * from Categories where CategoryID=8;
select ProductName,CategoryName,C.Description,UnitPrice from Products P join Categories C where P.CategoryID=C.CategoryID and  C.CategoryID=8;
select  * from Employees;
select FirstName,LastName from Employees;
select FirstName,LastName,Title from Employees where Title like '%Manager';
select distinct Title from Employees;
select * from Employees where Salary between 2000 and 2500;
select CompanyName,ProductName from Suppliers S join Products P on S.SupplierID=P.SupplierID where CompanyName='Tokyo Traders';
select count(*) as 'No Of Suppliers' from suppliers;
select Round(sum(Salary)) from Employees;
select Min(UnitPrice) from Products;
select Avg(UnitPrice) from Products;
select Max(UnitPrice) from Products;
Select Suppliers.SupplierID,count(ProductName) NoOfItemsSupplied from Products join Suppliers on Products.SupplierID=Suppliers.SupplierID group by Suppliers.SupplierID;
Select Avg(UnitPrice),C.CategoryID from Categories C join Products P on P.CategoryID=C.CategoryID group by C.CategoryID;
select Count(*) ,S.SupplierID from Suppliers S join Products P on P.SupplierID=S.SupplierID group by S.SupplierID having count(*)>=5;
select ProductID,ProductName,ceil(UnitPrice*UnitsInStock )as InventoryValue from Products order by InventoryValue desc,ProductName;